# Site settings
title: This is my blog
email: helloquico@gmail.com
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://fdelacruz.github.io" # the base hostname & protocol for your site
twitter_username: fdelacruz
github_username:  fdelacruz

include:  ['_pages']
relative_permalinks: false

excerpt_separator: "{{ more }}"

paginate: 5
paginate_path: "/page:num"

permalink: "/:year/:month/:day/:title"

# Build settings
markdown: kramdown
