# Site settings
title: Francisco De La Cruz
email: helloquico@gmail.com
description: This is where I share my work. When I'm not making beautiful things, I'm practicing yoga, biking, drinking good coffee, and more.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://fdelacruz.github.io" # the base hostname & protocol for your site
twitter_username: fdelacruz
github_username:  fdelacruz

include:  ['_pages']
relative_permalinks: false

excerpt_separator: "{{ more }}"

paginate: 5
paginate_path: "/page:num"

# Build settings
markdown: kramdown
